export type IconName =
    | "account"
    | "chart"
    | "chevron-left"
    | "chevron-right"
    | "close-drawer"
    | "cloud-upload"
    | "cog-outlined"
    | "create-account"
    | "credit-card"
    | "dashboard"
    | "open-drawer"
    | "plus"
    | "signout"
    | "plus-circle";
